version: "3.8"

services:
  db:
    image: mysql:8.0
    volumes:
      - docker-compose-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: docker_compose_db
    ports:
      - 3307:3306

  web:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      # 開発用のイメージを作成する
      target: dev
    # フォアグラウンドで入力のための仮想端末が起動し続ける(プロセスが終了しない)
    tty: true
    # コンテナの標準入力をオープンにしたままにする
    stdin_open: true
    # バインドマウント
    volumes:
      - .:/go/src/app
      # ホストの8080に来たリクエストをコンテナの8080に送る
    ports:
      - 8080:8080
    # 依存の向き「web → db」
    # dbを起動してからwebを起動する
    depends_on:
      - db

volumes:
  docker-compose-db: